# Import Libreries

In [22]:
import pandas as pd 
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [26]:
df = pd.read_csv('Experiance_Analytics_data.csv')

In [19]:
df1 = pd.read_csv('user_engagement.csv')

In [27]:
df

,MSISDN/Number,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),Activity Duration UL (ms),Activity Duration DL (ms),Handset Manufacturer,Handset Type,Avg RTT DL,Avg Bearer TP,Avg TCP Retrans,Avg Activity Duration,Avg RTT,cluster
0,0.000000e+00,60.051345,14.283619,16710.132029,1376.96088,1.379041e+06,106439.684597,582189.398533,680318.982885,Samsung,undefined,74.334963,18087.09291,107871.684597,1.367039e+06,74.334963,1
1,3.360100e+10,46.000000,0.000000,37.000000,39.00000,0.000000e+00,0.000000,33662.000000,26588.000000,Huawei,Huawei P20 Lite Huawei Nova 3E,46.000000,76.00000,0.000000,1.082040e+05,46.000000,1
2,3.360100e+10,30.000000,1.000000,48.000000,51.00000,0.000000e+00,0.000000,54751.000000,49283.000000,Apple,Apple iPhone 7 (A1778),31.000000,99.00000,0.000000,2.326460e+05,31.000000,1
3,3.360100e+10,0.000000,0.000000,48.000000,49.00000,0.000000e+00,0.000000,18434.000000,16793.000000,undefined,undefined,0.000000,97.00000,0.000000,4.972000e+04,0.000000,1
4,3.360101e+10,69.000000,15.000000,204.000000,44.00000,1.066000e+03,0.000000,4497.000000,12097.000000,Apple,Apple iPhone 5S (A1457),84.000000,248.00000,765968.000000,9.558650e+05,84.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95250,3.378996e+10,0.000000,0.000000,41.000000,65.00000,0.000000e+00,0.000000,36809.000000,34172.000000,Samsung,Samsung Galaxy S8 Plus (Sm-G955F),0.000000,106.00000,0.000000,6.985700e+04,0.000000,1
95251,3.378997e+10,48.000000,5.000000,23.000000,44.00000,0.000000e+00,0.000000,48886.000000,35138.000000,Apple,Apple iPhone 6S (A1688),53.000000,67.00000,0.000000,7.498500e+04,53.000000,1
95252,3.378998e+10,0.000000,0.000000,42.000000,52.00000,0.000000e+00,0.000000,51136.000000,40049.000000,undefined,undefined,0.000000,94.00000,0.000000,7.738200e+04,0.000000,1
95253,3.379000e+10,42.000000,10.000000,9978.000000,387.00000,2.150440e+05,3001.000000,241044.000000,259862.000000,Huawei,Huawei Honor 9 Lite,52.000000,10365.00000,3001.000000,2.929050e+05,52.000000,1
95254,3.379000e+10,34.000000,6.000000,68.000000,48.00000,0.000000e+00,0.000000,39006.000000,33435.000000,Apple,Apple iPhone 8 Plus (A1897),40.000000,116.00000,0.000000,4.178400e+04,40.000000,1

In [30]:
# Drop the MSISDN/Number column 
features = df1.drop(columns=['MSISDN/Number'])

# Standerdize the features 
scaler = StandardScaler()
df_scaled = scaler.fit_transform(features)

# Perform k-means clustring 
kmeans = KMeans(n_clusters=3, random_state=42)
df1['cluster'] = kmeans.fit_predict(df_scaled)

# Determine the less engagged cluster by comparing cluster cetroids 
centroids = kmeans.cluster_centers_
less_engaged_cluster = np.argmin(np.sum(centroids, axis=1))

# Calculate Euclidean distance from each user to the less engaged cluster centroid 
less_engaged_centroid = centroids[less_engaged_cluster]
df1['engagement_score'] = np.linalg.norm(df_scaled - less_engaged_centroid, axis=1)
print(df1[['MSISDN/Number', 'cluster', 'engagement_score']])

       MSISDN/Number  cluster  engagement_score
0       0.000000e+00        2        835.126728
1       3.360100e+10        1          0.880424
2       3.360100e+10        1          1.099128
3       3.360100e+10        1          0.749914
4       3.360101e+10        1          1.206816
...              ...      ...               ...
95250   3.378996e+10        1          0.904815
95251   3.378997e+10        1          0.863047
95252   3.378998e+10        1          0.814420
95253   3.379000e+10        1          1.099885
95254   3.379000e+10        1          0.834527

[95255 rows x 3 columns]

In [31]:
#Drop non-numeric and identifiercolumns for clustring 
df_features = df.drop(columns=['MSISDN/Number','Handset Manufacturer', 'Handset Type', 'cluster'] )

In [ ]:
# Standerdize the features 
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_features)

#Perform K-means clustring 
kmeans = KMeans(n_clusters=3, random_state=42)
df['cluster'] = kmeans.fit_predict(df_scaled) 

#Determine the worst experience cluster by comparing cluster by cetroinds 
centroids = kmeans.cluster_centers_
worst_experience_cluster = np.argmax(np.sum(centroids, axis=1))

#Calculate euclidean distance from each user to the worst experience cluster centroid 
worst_experience_centroid = centroids[worst_experience_cluster]