In [25]:
#import libraries
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [4]:
df = pd.read_csv('Telecom_challenge_dataset.csv')

In [5]:
df

,Unnamed: 0,Number_of_xDR_Sessions,Start,Start ms,End,End ms,Session_Duration,IMSI,MSISDN/Number,IMEI,...,Total_UL,Total_DL,Social_Media_Total,Google_Total,Email_Total,Youtube_Total,Netflix_Total,Gaming_Total,Other_Total,Decile
0,62,1.304243e+19,4/21/2019 2:55,73.0,4/25/2019 0:17,262.0,336160.0,2.082018e+14,3.376353e+10,8.637690e+13,...,46797611.0,632600264.0,2306304.0,12508343.0,2947986.0,33785357.0,27059520.0,586723162.0,461046993.0,9
1,65,1.311448e+19,4/21/2019 8:26,605.0,4/25/2019 1:20,655.0,320001.0,2.082017e+14,3.366364e+10,3.564211e+13,...,18261248.0,597244693.0,2079990.0,10947068.0,2016170.0,24438238.0,21198618.0,553525983.0,143391779.0,9
2,66,7.349883e+18,4/21/2019 8:54,105.0,4/25/2019 0:48,931.0,316419.0,2.082019e+14,3.366010e+10,3.579881e+13,...,50065095.0,538809148.0,2788022.0,4124132.0,1921045.0,26221282.0,33016593.0,517411244.0,351957444.0,9
3,67,1.311448e+19,4/21/2019 9:19,590.0,4/25/2019 4:42,965.0,329003.0,2.082021e+14,3.365079e+10,3.575751e+13,...,29436200.0,162196572.0,1587744.0,12497259.0,633163.0,23264606.0,21560614.0,126031552.0,489909991.0,9
4,68,1.304243e+19,4/21/2019 10:09,1.0,4/25/2019 1:39,272.0,314961.0,2.082014e+14,3.366274e+10,3.528141e+13,...,50576233.0,93360974.0,2488677.0,3504964.0,1399164.0,41043086.0,26529939.0,62498650.0,531681682.0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125552,149994,1.311448e+19,4/29/2019 7:28,83.0,4/30/2019 15:01,268.0,113545.0,2.082003e+14,3.364566e+10,3.515541e+13,...,59377936.0,862796008.0,892867.0,8922614.0,1565542.0,42219856.0,28354119.0,825524976.0,792559807.0,6
125553,149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,...,57628851.0,574175259.0,3517065.0,12784914.0,690876.0,27955095.0,37561864.0,535806880.0,16751926.0,3
125554,149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,...,39135081.0,666648844.0,2352181.0,4415361.0,2121718.0,22165518.0,40643294.0,631628095.0,714638145.0,5
125555,149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,...,34912224.0,592786405.0,1260239.0,6585469.0,2058277.0,24516413.0,15029702.0,566933800.0,132415585.0,5
125556,149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,...,29626096.0,371895920.0,823109.0,7757267.0,2850914.0,17122508.0,16494842.0,355066446.0,816120043.0,5

# Show Sample of dataset

In [6]:
df.sample(5)

,Unnamed: 0,Number_of_xDR_Sessions,Start,Start ms,End,End ms,Session_Duration,IMSI,MSISDN/Number,IMEI,...,Total_UL,Total_DL,Social_Media_Total,Google_Total,Email_Total,Youtube_Total,Netflix_Total,Gaming_Total,Other_Total,Decile
84752,101806,1.311448e+19,4/26/2019 15:55,516.0,4/29/2019 8:13,391.0,231506.0,2.082018e+14,3.366805e+10,3.537771e+13,...,32597372.0,521001500.0,3549337.0,1855548.0,1209364.0,28467555.0,31983189.0,484539018.0,93806233.0,9
62002,74163,7.277826e+18,4/26/2019 9:01,771.0,4/27/2019 9:01,797.0,86400.0,2.082018e+14,3.368002e+10,3.586241e+13,...,32382735.0,602568479.0,3049457.0,6003388.0,1262937.0,13293843.0,31416872.0,566431211.0,49665630.0,4
11793,14980,6.917538e+18,4/24/2019 18:47,818.0,4/24/2019 23:53,515.0,18340.0,2.082010e+14,3.361696e+10,3.548271e+13,...,43139899.0,209031247.0,3073503.0,12137745.0,1915177.0,32065412.0,36934598.0,165466217.0,458966558.0,0
8086,10595,6.917538e+18,4/24/2019 17:02,23.0,4/25/2019 1:31,494.0,30530.0,2.082015e+14,3.362823e+10,3.520471e+13,...,35078026.0,601060642.0,1602185.0,4518119.0,3141226.0,22732105.0,36731593.0,566235824.0,400621709.0,1
115506,137450,7.349883e+18,4/29/2019 1:44,714.0,4/30/2019 3:10,524.0,91587.0,2.082019e+14,3.366899e+10,3.561451e+13,...,58734688.0,856714544.0,1797116.0,9575798.0,989983.0,21933587.0,26733835.0,838231809.0,401674825.0,5

In [7]:
df.columns

Index(['Unnamed: 0', 'Number_of_xDR_Sessions', 'Start', 'Start ms', 'End',
       'End ms', 'Session_Duration', 'IMSI', 'MSISDN/Number', 'IMEI',
       'Last Location Name', 'Avg RTT DL (ms)', 'Avg RTT UL (ms)',
       'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 37500B < Vol UL',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with 6250B < Vol UL < 37500B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social_Media_DL', 'Social_Media_UL', 'Google_DL', 'Google_UL',
       'Email_DL', 'Email_UL', 'Youtube_DL', 'Youtube_UL', 'Netflix_DL',
       'Netflix_UL', 'Gaming_DL', 'Gaming_UL', 'Other_DL', 'Other_UL',
       'Total_UL', 'Total_DL', 'Social_Media_Total', 'Google_Total',
       'Email_Total', 'Youtube_Total', 'Netflix_Total', 'Gaming_Total',
       'Other_Total', 'Decile'],
      dtype='object')

In [12]:
# Add a total traffic column 
df['total_traffic'] = df['Total_DL'] + df['Total_UL']

In [22]:
# Aggregate engagement metrics per customer id (MSISDN/Number)
user_engagement = df.groupby('MSISDN/Number').agg({
    'Number_of_xDR_Sessions':'sum',
    'Session_Duration':'sum', 
    'Social_Media_DL':'sum',
    'Social_Media_UL':'sum', 
    'Google_DL':'sum',
    'Google_UL':'sum',
    'Email_DL':'sum',
    'Email_UL':'sum', 
    'Youtube_DL':'sum',
    'Youtube_UL':'sum', 
    'Netflix_DL':'sum',
    'Netflix_UL':'sum',
    'Gaming_DL':'sum',
    'Gaming_UL':'sum',
    'Other_DL':'sum',
    'Other_UL':'sum',
    'Total_UL':'sum',
    'Total_DL':'sum',
    'Social_Media_Total':'sum',
    'Google_Total':'sum',
    'Email_Total':'sum', 
    'Youtube_Total':'sum',
    'Netflix_Total':'sum',
    'Gaming_Total':'sum',
    'Other_Total':'sum',
}).reset_index

In [26]:
# Reporting the top 10 customers per engagement metric
top_10_frequency = user_engagement.nlargest(10, 'Number_of_xDR_Sessions')
top_10_duration = user_engagement.nlargest(10, 'session_duration')
top_10_traffic = user_engagement.nlargest(10, 'total_traffic')

print("Top 10 customers by session frequency:\n", top_10_frequency)
print("Top 10 customers by session duration:\n", top_10_duration)
print("Top 10 customers by total traffic:\n", top_10_traffic)

AttributeError: 'function' object has no attribute 'nlargest'

In [27]:
top_10_frequency = user_engagement.sort_values(by='Number_of_xDR_Sessions',ascending=False).head(10)

AttributeError: 'function' object has no attribute 'sort_values'